# dependencies fixed for reproducibility
name: tudat-examples
channels:
  - conda-forge
  - tudat-team
dependencies:
  - tudatpy>=0.10
  - numpy
  - scipy
  - ipython
  - ipykernel
  - nbconvert # for create_script.py utility
  - tqdm # for create_script.py utility
